version: '3'

services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11.3
    volumes:
     - /shared/project/data/cassandra/data:/var/lib/cassandra
     - /shared/project/data/cassandra/scripts:/scripts
    ports:
     - "7000:7000"
     - "9042:9042"
    environment:
     - CASSANDRA_CLUSTER_NAME=cscie63_cluster

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.179.12
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "engine-stream:1:1,engine-alert:1:1"
    depends_on:
      - zookeeper
