services:
  sparkmaster:
    image: modspark
    security_opt:
      - no-new-privileges
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
     - spark
    cap_drop:
     - ALL
    volumes:
     - "/var/jenkins/workspace/Wales:/media:ro"
    command:
      bin/spark-class org.apache.spark.deploy.master.Master

  sparkworker:
    image: modspark
    security_opt:
      - no-new-privileges
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
     - spark
    cap_drop:
     - ALL
    ports:
     - "8081:8081"
    volumes:
     - "/var/jenkins/workspace/Wales:/media:ro"
    command: >
      bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077

  cassandra:
    image: cassandra:3.11.3
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
     - spark
    environment:
     - CASSANDRA_CLUSTER_NAME=cscie63_cluster

  zookeeper:
    image: owlab/zookeeper-arm64
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
     - spark

  kafka:
    image: wurstmeister/kafka
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - spark
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "engine-stream:1:1,engine-alert:1:1"
    depends_on:
      - zookeeper

networks:
  spark:
    driver: overlay
    attachable: true
  kafka:
    driver: overlay
    attachable: true
